backend/modules/forum/models/Thread.php
<?php

namespace backend\modules\forum\models;

use Yii;
use yii\helpers\Url;
use yii\db\Query;

/**
 * This is the model class for table "{{%forum_thread}}".
 *
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $user_id
 * @property integer $board_id
 * @property integer $post_count
 */
class Thread extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%forum_thread}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['content'], 'string'],
            [['created_at', 'user_id', 'board_id', 'post_count', 'updated_at'], 'integer'],
            [['title'], 'string', 'min' => 2, 'max' => 80],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'content' => Yii::t('app', 'Content'),
            'created_at' => Yii::t('app', 'Create Time'),
            'user_id' => Yii::t('app', 'User ID'),
            'board_id' => Yii::t('app', 'Block ID'),
            'post_count' => Yii::t('app', 'Post Count')
        ];
    }

    /**
     * This is invoked before the record is saved.
     * @return boolean whether the record should be saved.
     */
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->user_id = Yii::$app->user->id;
                $this->created_at = time();
                $this->updated_at = time();
            }
            return true;
        } else {
            return false;
        }
    }
    
    /**
     *string the URL that shows the detail of the thread
     */
    public function getUrl()
    {
    	 return Url::toRoute(['/forum/thread/view', 'id' => $this->id]);
    }

    public function getUser()
    {
        return Yii::$app->db
            ->createCommand("SELECT id, username, avatar FROM {{%user}} WHERE id={$this->user_id}")
            ->queryOne();
    }
    
    public function getForum()
    {
        return Yii::$app->db
            ->createCommand("SELECT * FROM {{%forum}} as f JOIN {{%forum_board}} as b ON f.id=b.forum_id WHERE b.id={$this->board_id}")
            ->queryOne();
    }
    
    public function getBoard()
    {
        return Yii::$app->db
            ->createCommand("SELECT id, name, user_id FROM {{%forum_board}} WHERE id={$this->board_id}")
            ->queryOne();
    }
    
    public function isFavor()
    {
        $query = new Query;
        return $query->select('id')
		  ->from('{{%post_favor}}')
		  ->where('post_id=:id and user_id=:user_id', [':id'=>$this->id, ':user_id'=>Yii::$app->user->id])
          ->exists();
    }

    public function isOneBoard()
    {
        $forum_id = $this->forum['forum_id'];
        $count = Yii::$app->db
            ->createCommand("SELECT count(*) FROM {{%forum_board}} WHERE forum_id={$forum_id}")
            ->queryScalar();
        return ($count == 1) ? true : false;
    }

    /**
     * 获取回复的帖子
     * @return array
     */
    public function getPosts()
    {
        $query = new Query;
        $query->select('p.id,  p.content, p.created_at, p.user_id, u.username, u.avatar')
            ->from('{{%forum_post}} as p')
            ->join('LEFT JOIN','{{%user}} as u', 'u.id=p.user_id')
            ->where('p.thread_id=:id', [':id' => $this->id]);
        $result = Yii::$app->tools->Pagination($query);
        return ['posts' => $result['result'], 'pages' => $result['pages']];
    }

    /**
     * 获取SEO信息，标题，关键字，描述
     * @return array ['title', 'keywords', 'description']
     */
    public function getSeoInfo()
    {
        $data = strip_tags($this->content);
        $title = (empty($this->title)) ? mb_substr($data, 0, 80) : $this->title;
        $description = mb_substr($data, 0, 200, 'utf-8');
        $keywords = $title;
        return [
            'title' => $title,
            'keywords' => $keywords,
            'description' => $description
        ];
    }
}

backend/modules/forum/controllers/ThreadController.php
<?php

namespace backend\modules\forum\controllers;

use Yii;
use backend\modules\forum\models\Thread;
use backend\modules\forum\models\ThreadSearch;
use backend\modules\forum\models\Post;
use common\components\BaseController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\Pagination;

/**
 * ThreadController implements the CRUD actions for Thread model.
 */
class ThreadController extends BaseController
{
    public $layout = 'forum';
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'upload' => [
                'class' => 'common\widgets\umeditor\UMeditorAction',
            ]
        ];
    }

    /**
     * Lists all Thread models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ThreadSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }
    
    /**
     * Displays a single Thread model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $newPost = new Post();
        
        if ($newPost->load(Yii::$app->request->post())) {
            $newPost->thread_id = $model->id;
            if ($newPost->save()){
                Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Create successfully.'));
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } 

        return $this->render('view', [
            'model' => $model,
            'newPost' => $newPost,
        ]);
    }

    /**
     * Creates a new Thread model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Thread();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Thread model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Saved successfully'));
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Thread model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $board_id = $model->board_id;
        Post::deleteAll(['thread_id' => $model->id]);
        $model->delete();
        Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Deleted successfully.'));
        return $this->redirect(['/forum/thread/index']);
    }

    /**
     * Finds the Thread model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Thread the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Thread::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/forum/views/thread/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\forum\models\Thread */
/* @var $form yii\bootstrap\ActiveForm */
?>

<div class="thread-form">
    <?php if (!Yii::$app->user->isGuest) :?>
        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'id', [
            'template' => "<div class=\"input-group\"><span class=\"input-group-addon\">". Yii::t('app', 'Id') ."</span>{input}</div>",
        ])->textInput(['maxlength' => 128, 'autocomplete'=>'off'])
        ?>

        <?= $form->field($model, 'board_id', [
            'template' => "<div class=\"input-group\"><span class=\"input-group-addon\">". Yii::t('app', 'Board Id') ."</span>{input}</div>",
        ])->textInput(['maxlength' => 128, 'autocomplete'=>'off'])
        ?>

        <?= $form->field($model, 'title', [
            'template' => "<div class=\"input-group\"><span class=\"input-group-addon\">". Yii::t('app', 'Title') ."</span>{input}</div>",
        ])->textInput(['maxlength' => 128, 'autocomplete'=>'off'])
        ?>

        <?= $form->field($model, 'content')->widget('common\widgets\umeditor\UMeditor', [
            'clientOptions' => [
                'initialFrameHeight' => 100,
                'toolbar' => [
                    'source | undo redo | bold |',
                    'link unlink | emotion image video |',
                    'justifyleft justifycenter justifyright justifyjustify |',
                    'insertorderedlist insertunorderedlist |' ,
                    'horizontal preview fullscreen',
                ],
            ]
        ])->label(false) ?>

        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary', 'autocomplete'=>'off']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    <?php else: ?>
        <h3>Welcom to <?= Html::encode($forumName); ?></h3>
    <?php endif; ?>
</div>

backend/modules/forum/views/thread/_posts.php
<?php 

use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\widgets\LinkPager;
use shiyang\infinitescroll\InfiniteScrollPager;

$floor = 1;
if (isset($_GET['page']) >= 2) //分页标识大于2才开始计算
    $floor += ($pageSize * $_GET['page']) - $pageSize;
?>
<section class="posts">
    <div class="post-title">
        <h3><?= Yii::t('app', '{postCount} comments', ['postCount' => $postCount]) ?></h3>
    </div>
    <div id="post-list">
        <?php foreach($posts as $post):
            $floor_number=$floor++; //楼层数减少
            ?>
            <div class="row post-item">
                <div class="col-sm-12">
                    <div class="post-meta">
                        <?= Html::a('<span class="glyphicon glyphicon-user"></span> ' . Html::encode($post['username']), ['/user/view', 'id' => $post['username']]) ?>
                        &nbsp;•&nbsp;
                        <span class="post-time">
                            <span class="glyphicon glyphicon-time"></span> <?= Yii::$app->formatter->asRelativeTime($post['created_at']) ?>
                        </span>
                        <a class="floor-number" id="<?= $floor_number ?>" href="#<?= $floor_number ?>">
                           <span class="badge"><?= $floor_number ?>#</span>
                        </a>
                    </div>
                    <div class="post-content">
                        <?= HtmlPurifier::process($post['content']) ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
        <?= LinkPager::widget([
            'pagination' => $pages,
            'lastPageLabel' => true,
            'firstPageLabel' => true
        ]);?>
    </div>
</section>

backend/modules/forum/views/thread/_view.php
<?php 
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\Url;

$user = $data->user;
?>
<article class="thread-view">
    <header class="thread-head">
        <h1><?= Html::a(Html::encode($data->title), $data->url) ?></h1>
        <div class="thread-info">
            <span class="glyphicon glyphicon-user"></span> <?= Html::a(Html::encode($user['username']), ['/user/view', 'id' => $user['id']]) ?>
            &nbsp;•&nbsp;
            <span class="glyphicon glyphicon-time"></span> <?= Yii::$app->formatter->asRelativeTime($data->created_at) ?>
            <div class="pull-right">
                <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Delete'), ['/user/view', 'id' => $user['id']]) ?>
                <span class="glyphicon glyphicon-comment"></span> <?= $data->post_count ?>
                &nbsp;<a href="<?= Url::toRoute(['/forum/thread/delete', 'id' => $thread['id']]) ?>"  data-confirm="<?= Yii::t('app', 'Are you sure to delete it?') ?>" data-method="post">
                    <span class="glyphicon glyphicon-trash"></span> <?= Yii::t('app', 'Delete') ?>
                </a>
            </div>
        </div>
    </header>
    <article class="thread-main">
         <?= HtmlPurifier::process($data->content) ?>
    </article>
</article>

backend/modules/forum/views/thread/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */

$this->title = Yii::$app->setting->get('siteTitle');
?>
<div class="thread-index">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>
        <?= Html::a(Yii::t('app', 'Create Thread'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <div class="thread-all">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                'id',
                'title:ntext',
                [
                    'attribute' => 'content',
                    'value' => function ($model) {
                        return mb_substr($model->content, 0, 200, 'utf-8');
                    }
                ],
                'user_id',
                'created_at:time',
                ['class' => 'yii\grid\ActionColumn'],
            ],
            'options' => [
                'class' => 'table-responsive'
            ]
        ]); ?>
    </div>
</div>

backend/modules/forum/views/thread/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\modules\forum\models\Post */

$seoInfo = $model->seoInfo;
$this->title = $seoInfo['title'];
$this->registerMetaTag(['name' => 'keywords', 'content' => $seoInfo['keywords']]);
$this->registerMetaTag(['name' => 'description', 'content' => $seoInfo['description']]);

$this->params['forum'] = $model->forum;
$this->params['breadcrumbs'][] = $model->user['username'];
?>
<div class="widget-container">
    <?= $this->render('_form', ['model'=>$model]); ?>
</div>

backend/modules/forum/views/thread/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\HtmlPurifier;

/* @var $this yii\web\View */
/* @var $model backend\modules\forum\models\Post */

$seoInfo = $model->seoInfo;
$this->title = $seoInfo['title'];
$this->registerMetaTag(['name' => 'keywords', 'content' => $seoInfo['keywords']]);
$this->registerMetaTag(['name' => 'description', 'content' => $seoInfo['description']]);
$this->params['forum'] = $model->forum;
$user = $model->user;
$posts = $model->posts;
$board = $model->board;
if (!$model->isOneBoard()):
    $this->params['breadcrumbs'][] = ['label' => $board['name'], 'url' => ['/forum/board/view', 'id' => $board['id']]];
endif;
$this->params['breadcrumbs'][] = $user['username'];
?>
<div class="row">
    <div class="col-sm-9">
        <article class="thread-view">
            <header class="thread-head">
                <h1><?= Html::a(Html::encode($model->title), $model->url) ?></h1>
                <div class="thread-info">
                    <span class="glyphicon glyphicon-user"></span> <?= Html::a(Html::encode($user['username']), ['/user/view', 'id' => $user['id']]) ?>
                    &nbsp;•&nbsp;
                    <span class="glyphicon glyphicon-time"></span> <?= Yii::$app->formatter->asRelativeTime($model->created_at) ?>
                    <div class="pull-right">
                        <span class="glyphicon glyphicon-comment"></span> <?= $model->post_count ?>
                        <?php if ($user['id'] == Yii::$app->user->id || $board['user_id'] == Yii::$app->user->id): ?>
                            <a href="<?= Url::toRoute(['/forum/thread/update', 'id' => $model['id']]) ?>">
                                <span class="glyphicon glyphicon-pencil"></span> <?= Yii::t('app', 'Update') ?>
                            </a>
                            &nbsp;<a href="<?= Url::toRoute(['/forum/thread/delete', 'id' => $model['id']]) ?>"  data-confirm="<?= Yii::t('app', 'Are you sure to delete it?') ?>" data-method="post">
                                <span class="glyphicon glyphicon-trash"></span> <?= Yii::t('app', 'Delete') ?>
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
            </header>
            <article class="thread-main">
                <?= HtmlPurifier::process($model->content) ?>
            </article>
        </article>

        <!-- Post Form End -->
        <?= $this->render('_posts', [
                'posts'=>$posts['posts'],
                'pageSize'=>$posts['pages']->pageSize, //分页
                'pages' => $posts['pages'], //分页
                'postCount' => $model->post_count //评论数
            ]);
        ?>
    </div>
    <div class="col-sm-3">
        <aside class="user-info">
            <div class="hidden-xs">
                <img class="img-circle img-user" src="<?= Yii::getAlias('@avatar') . $user['avatar'] ?>" alt="User avatar">
            </div>
            <div class="user-msg">
                <strong><?= Html::a(Html::encode($user['username']), ['/user/view', 'id' => $user['username']]) ?></strong>
            </div>
        </aside>
    </div>
</div>